#pragma once

const int ROUNDS = 20; // number of rounds in game
const int BOARDSIZE = 26; // board size
const int PASS_GO = 200; // amount you get for passing go
const char POUND = 156; // sybol for pound
const double JAIL_FEE = 50; // fee needed to be paid when you go in jail
const int JAIL_POSITION = 6; // stores position of jail
const double STATION_COST = 200; //cost to buy station 
const double STATION_FEE = 10; // sued for bonus
const double FIND_MONEY = 20; // sued for bonus
const double CODING_COMPETITION = 50; // sued for bonus
const double RENT_REBATE = 100; // sued for bonus
const double LOTTERY = 150; // sued for bonus
const double BEQUEST = 200; // sued for bonus
const double BIRTHDAY = 300; // sued for bonus
const double STARBUCKS = 20; // used for penalty
const double BROADBAND = 50; // used for penalty
const double SU_SHOP = 100; // used for penalty
const double ASSIGNMENT_SOLUTION = 150; // used for penalty
const double ROMANTIC_MEAL = 200; // used for penalty
const double UNIVERSITY_FEES = 300; // used for penalty
const int ACTION1 = 1; // used for actions with bonus and penalty
const int ACTION2 = 2; // used for actions with bonus and penalty
const int ACTION3 = 3; // used for actions with bonus and penalty
const int ACTION4 = 4; // used for actions with bonus and penalty
const int ACTION5 = 5; // used for actions with bonus and penalty
const int ACTION6 = 6; // used for actions with bonus and penalty
const int SQUARE_COLOUR0 = 0; // used to show colour group index
const int SQUARE_COLOUR1 = 1; // used to show colour group index
const int SQUARE_COLOUR2 = 2; // used to show colour group index
const int SQUARE_COLOUR3 = 3; // used to show colour group index
const int SQUARE_COLOUR4 = 4; // used to show colour group index
const int SQUARE_COLOUR5 = 5; // used to show colour group index
const int SQUARE_COLOUR6 = 6; // used to show colour group index
const int SQUARE_COLOUR7 = 7; // used to show colour group index
const int SQUARE_GATHERED2 = 2;  // used for colour groups that need 2
const int SQUARE_GATHERED3 = 3; // used for colour groups that need 3
const double DOUBLE_RENT = 2; // used when rent should be doubled
const double NORMAL_RENT = 1; // used when rent is normal
const double NO_MONEY = 0; // used for no money
const int MAX_BANKRUPT_PLAYERS = 3; // used to show max number of bankrupt users